### ISSUE TITLE
Revert to original functionality

### ISSUE THREAD

**Issue by mjsir911** [janlazo/vim-bang-terminal#1]
Hello, and thank you for creating this,

I was wondering if there was any way to run a command how neovim would natively run the command ie in the background?

**Comment by janlazo** [comment]
Do you want a toggle or to control the remapping yourself? I can use `autoload/` to expose a public function if that's more convenient.

**Comment by mjsir911** [comment]
I am looking to be able to run specific commands asynchronously. Not so much toggle but perhaps controlling the remapping myself. 

I'm not sure about any specific use cases I have right now, but neovim decided asynchronous commands are important for some reason, and I was hoping to use this plugin while still using asynchronous commands for when they are fitting.

**Comment by janlazo** [comment]
Is `jobstart` insufficient for asynchronous background jobs? `:!` is suppose to be synchronous and `:terminal` is used in this plugin to support interactive commands.

Can you give me an example for backgrounding an interactive command via `:terminal`? It can be any command as long as you give a brief description of what it does.
